services:
  configurator:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    pull_policy: build
    restart: unless-stopped
    env_file: stack.env
    ports:
      - "3000:3000"
    networks:
      - proxy
      - redis-net
  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    volumes:
      - redisinsight:/data
    networks:
      - redis-net
  cache:
    image: redis:7
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - redis-net
    volumes:
      - cache:/data
networks:
  conf:
  redis-net:
    external: true
  proxy:
    external: true
volumes:
  cache:
  redisinsight: